version: '3.8'

services:
  php-app:
    build: .
    restart: "no"
    ports:
      - "3001:80"
    depends_on:
      - mysql-app
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7
    restart: "no"
    container_name: mysql-app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./employees.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-app
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - mysql-app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: overlay
    attachable: true

